### ISSUE TITLE
Denying generation of flash package.

### ISSUE THREAD

**Issue by pshtif** [ibilon/chxdoc#2]
Hi guys, it seems its impossible to generate documentation without including the flash package. I can deny all the other internals like / or haxe.\* but if I deny flash.\* or even through --policy=deny --allow=com.\* it will crash

Uncaught exception - Unable to locate package flash.display for flash.display.Sprite

Any help would be appreciated.

**Comment by heybdj** [comment]
I found a way around that exception that suited our purposes. Hopefully it will help you, too :)

Open up ClassHandler.hx under `[root haxelib folder]/chxdoc/git/chxdoc`. You'll have to edit line 213 in the `getIsPrivate()` function. Change it from `if(sc == null)` to `if(sc == null || Filters.isFiltered( sc.path, false ))`. Reinstall the chxdoc command by running `haxelib run chxdoc install` in whatever directory you originally installed it in. Then you should be good to go! :)
