### ISSUE TITLE
Crashed 

### ISSUE THREAD

**Issue by jinhoyoo** [ibilon/chxdoc#4]
I generated xml file from my own openfl project but it created the crash like below. 

```
$ chxdoc -o docs -f document.xml 
ChxDoc Generator 1.3.0 - (c) 2008-2012 Russell Weir
Called from ? line 1
Called from chxdoc/ChxDocMain.hx line 407
Called from chxdoc/ChxDocMain.hx line 1005
Called from chxdoc/ChxDocMain.hx line 1025
Called from haxe/rtti/XmlParser.hx line 87
Called from haxe/rtti/XmlParser.hx line 312
Called from haxe/rtti/XmlParser.hx line 322
Called from haxe/rtti/XmlParser.hx line 485
Uncaught exception - Invalid this
```

I'm using haxe 3.1.2 and haxelib 3.1.0-rc.4 on MacOSX. 

Here is the xml file I made. https://www.dropbox.com/s/4uymleewyhoykgp/document.xml
 I validate this file by XML lint but no error.

**Comment by davidyu** [comment]
I'm getting the same error:

```
ChxDoc Generator 1.3.0 - (c) 2008-2012 Russell Weir
Called from ? line 1
Called from chxdoc/ChxDocMain.hx line 407
Called from chxdoc/ChxDocMain.hx line 1005
Called from chxdoc/ChxDocMain.hx line 1025
Called from haxe/rtti/XmlParser.hx line 87
Called from haxe/rtti/XmlParser.hx line 312
Called from haxe/rtti/XmlParser.hx line 322
Called from haxe/rtti/XmlParser.hx line 485
Called from haxe/rtti/XmlParser.hx line 307
Uncaught exception - Invalid this
```

on haxe 3.1.0 and the latest std lib (dev) on OSX

FWIW, haxedoc generates documentation just fine.

**Comment by davidyu** [comment]
It looks like the XmlParser in the standard library handles "this," whereas the XmlParser in chxdoc doesn't. We'll just need to reintegrate XmlParser from the standard haxe library back into chxdoc, and re-add whatever modifications the authors made to XmlParser manually.

Does anyone have any better suggestions?

**Comment by davidyu** [comment]
Please see pull request for fix.

**Comment by ibilon** [comment]
Thanks for the pull request.
